### PR TITLE
Implement support for version from last git commit

### PR DESCRIPTION
**Pull request by pramodk**
- coreneuron version was printed as "version id unimplemented"
  - add cmake module GitRevision.cmake to find git commit information
  - this commit adds support to print project version along with
    git commit and it's date. e.g.
      Version : 0.21.0 bd747a8e (14-09-2020 16:03)

### CODE REVIEW

**Review by nrnhines — APPROVED** [review]

**Comment by pramodk** [comment]
@nrnhines : until this gets merged, may be you can just cherry-pick this commit into your branch and test your NEUERON PR?

**Comment by nrnhines** [comment]
Strange puzzle. I checked out this pull request ```Your branch is up to date with 'origin/pramodk/version-info'``` and
```
hines@hines-T7500:~/neuron/acell-thread/external/coreneuron$ git log
commit 2521f568c3eeb468700f0fafbc9b28b30622996b (HEAD -> pramodk/version-info, origin/pramodk/version-info)
Author: pramodk <pramod.s.kumbhar@gmail.com>
Date:   Tue Sep 15 01:09:14 2020 +0200
```
Finally, for NEURON,
```
hines@hines-T7500:~/neuron/acell-thread$ git show HEAD
commit c7c28a2679172382df76f4d735001a97bee290b3 (HEAD -> acell-thread)
Author: Michael Hines <michael.hines@yale.edu>
Date:   Tue Sep 15 09:38:16 2020 -0400

    Update to use coreneuron with version info.

diff --git a/external/coreneuron b/external/coreneuron
index bd747a8e..2521f568 160000
--- a/external/coreneuron
+++ b/external/coreneuron
@@ -1 +1 @@
-Subproject commit bd747a8e94117bbbe7c8646b8f1a83c0b214b179
+Subproject commit 2521f568c3eeb468700f0fafbc9b28b30622996b
```
But when I build and launch, I get the nrn version output instead of the coreneuron version. ie.
```
hines@hines-T7500:~/neuron/acell-thread/test/coreneuron$ python test_datareturn.py
CoreNEURON run
 
 Duke, Yale, and the BlueBrain Project -- Copyright 1984-2020
 Version : 0.21.0 c7c28a26 (15-09-2020 09:38)
```

**Comment by nrnhines** [comment]
By the way, if I launch ```nrniv-core -h``` the version is not printed and after all the option help is printed it ends with ```Aborted (core dumped)```

**Review by alexsavulescu — APPROVED** [review]

**Comment by pramodk** [comment]
> Strange puzzle. I checked out this pull request Your branch is up to date with 'origin/pramodk/version-info' and
> But when I build and launch, I get the nrn version output instead of the coreneuron version. ie.

Did you commit the commit submodule before launching cmake command? Let me try it and see what's happening.

I have now added `--version` option in nrniv-core:

```bash
$ ./bin/nrniv-core --version
CoreNEURON Version : 0.21.0 2521f56 (2020-09-15 01:09:14 +0200)
```

> By the way, if I launch nrniv-core -h the version is not printed and after all the option help is printed it ends with Aborted (core dumped)

seems like `--help` was not properly handled. I have changed logic a bit and now it exit cleanly.

**Comment by nrnhines** [comment]
>I have now added --version option in nrniv-core:
```
$ ./bin/nrniv-core --version
CoreNEURON Version : 0.21.0 2521f56 (2020-09-15 01:09:14 +0200)
```
That is interesting as
```
commit 57856bafbfdc634ed4276c0a9d4a15a3caced32a
Author: Pramod Kumbhar <pramod.s.kumbhar@gmail.com>
Date:   Tue Sep 15 22:14:46 2020 +0200

    Added --version CLI flag
```
and when I do a fresh build from an empty bldtst
```
hines@hines-T7500:~/neuron/acell-thread/bldtst$ cmake .. -DCMAKE_INSTALL_PREFIX=install -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON -DIV_DIR=$HOME/neuron/ivcmake/build/install
...
make -j install
...
hines@hines-T7500:~/neuron/acell-thread/bldtst$ which nrniv-core
/home/hines/neuron/acell-thread/bldtst/install/bin/nrniv-core
hines@hines-T7500:~/neuron/acell-thread/bldtst$ nrniv-core --version
CoreNEURON Version : 0.21.0 c7c28a26 (2020-09-15 09:38:16 -0400)
```
So there must be something stupidly obvious that I'm missing.

**Comment by nrnhines** [comment]
I wonder if, when one builds coreneuron as a submodule, the git commands from within the nrn build folder are getting some nrn git info instead of from nrn/external/coreneuron

**Comment by pramodk** [comment]
> I wonder if, when one builds coreneuron as a submodule, the git commands from within the nrn build folder are getting some nrn git info instead of from nrn/external/coreneuron

Ahh yes! my bad! I am using `CMAKE_SOURCE_DIR` which will be nrn directory with submodule:

```
  execute_process(
    COMMAND ${GIT_EXECUTABLE} log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_REVISION_SHA1
    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
  # get last commit date
  execute_process(
    COMMAND ${GIT_EXECUTABLE} show -s --format=%ci
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_REVISION_DATE
    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
```

**Comment by pramodk** [comment]
Please retest

**Comment by pramodk** [comment]
Retest this please

**Comment by pramodk** [comment]
Please retest

**Comment by pramodk** [comment]
Retest this please

**Comment by pramodk** [comment]
Retest this please

**Pull request merged**
