### PR TITLE
Profiler support

### PR DESCRIPTION
**Pull request by fouriaux**
support for Intel Vtune

### CODE REVIEW

**Comment by pramodk** [comment]
bg-q build was failing due to missing `mod2c` (Jenkins plan adjusted). Have to trigger this tomorrow due to partition unavailability.

**Comment by fouriaux** [comment]
After discussion

**Comment by pramodk** [comment]
@fouriaux : have you tested this on our system recently?

**Comment by fouriaux** [comment]
@pramodk, last time was in October. I will check it.

**Pull request closed without merging**
