### PR TITLE
Support SONATA report units

### PR DESCRIPTION
**Pull request by jorblancoa**
**Description**

Passes the report units to the libsonatareport library

**Use certain branches for the SimulationStack CI**

CI_BRANCHES:NEURODAMUS_CORE_BRANCH=sandbox/jblanco/report_units,SPACK_BRANCH=report_units,

### CODE REVIEW

**Comment by jorblancoa** [comment]
retest this jenkins please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Review by sergiorg-hpc — APPROVED** [review]

**Review by alkino — APPROVED** [review]

**Pull request merged**
