### PR TITLE
Summation reports on soma, compartment and section targets

### PR DESCRIPTION
**Pull request by jorblancoa**
**Description**

Add support for soma and section targets when using summation reports.

**Use certain branches for the SimulationStack CI**

CI_BRANCHES:NEURODAMUS_CORE_BRANCH=sandbox/jblanco/section_target,PYNEURODAMUS_BRANCH=sandbox/jblanco/section_target,

### CODE REVIEW

**Comment by sergiorg-hpc** [comment]
The Spack PR for the deployment modules is available here:
https://github.com/BlueBrain/spack/pull/1173

**Comment by pramodk** [comment]
@jorblancoa : this is still pending? 😮  lets get this reviewed. @alkino  : you can provide feedback? (will do the same once have bit free time)

**Review by alkino — APPROVED** [review]

**Comment by jorblancoa** [comment]
I'm not authorized to merge @pramodk  :D

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by jorblancoa** [comment]
retest this please

**Comment by olupton** [comment]
retest this please Jenkins

**Review by alexsavulescu — APPROVED** [review]

**Comment by jorblancoa** [comment]
retest this please

**Review by sergiorg-hpc — APPROVED** [review]

**Pull request merged**
