### PR TITLE
change mallinfo to mallinfo2

### PR DESCRIPTION
**Pull request by kotsaloscv**
change mallinfo to mallinfo2

### CODE REVIEW

**Review by alkino — APPROVED** [review]

**Comment by kotsaloscv** [comment]
Please retest

**Comment by kotsaloscv** [comment]
The mallinfo2() function was added in glibc 2.33.

In BB5 we have the version 2.17. That is why the CI is failing. Should we reconsider the malloc_info?

**Review by pramodk — APPROVED** [review]
LGTM

**Comment by olupton** [comment]
I re-triggered the pipeline (https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/6529) after fixes elsewhere and it passed; not 100% sure why it didn't update the status here. I suggest merging this.

**Comment by kotsaloscv** [comment]
Please retest

**Pull request merged**
