### PR TITLE
Add Phase API

### PR DESCRIPTION
**Pull request by tapaswenipathak**
This adds Caliper, CudaProfiling, CrayPat and Tau `phase` API.

I didn't find any Caliper, CudaProfiling, CrayPat and Tau API usage as such so just added the API implementation. I created `Caliper`,  `CudaProfiling`, `CrayPat` and `Tau` namespace, please let me know if you would prefer different design.

### CODE REVIEW

**Comment by tristan0x** [comment]
> I didn't find any Caliper, CudaProfiling, CrayPat and Tau API usage a

They are used here:
https://github.com/BlueBrain/CoreNeuron/blob/6635cf5a3938256dccc8e20f48c59a8e480861db/coreneuron/nrniv/profiler_interface.h#L167-L180

> I created `Caliper`, `CudaProfiling`, `CrayPat` and `Tau` namespace, please let me know if you would prefer different design.

`coreneuron::detail::Instrumentor` class provides an abstraction layer on top of the different instrumentors (`coreneuron::detail::Caliper`, `coreneuron::detail::CudaProfiling`, ...).

So the scope API this PR should provide may use this `coreneuron::detail::Instrumentor` class instead.

**Comment by tapaswenipathak** [comment]
I don't think I get you. `template <class... TProfilerImpl>` is being implemented like

```c++
using Instrumentor = detail::Instrumentor<
#if defined CORENEURON_CALIPER
    detail::Caliper,
#endif
#if defined(CUDA_PROFILING)
    detail::CudaProfiling,
#endif
#if defined(CRAYPAT)
    detail::CrayPat,
#endif
#if defined(TAU)
    detail::Tau,
#endif
    detail::NullInstrumentor>;
```

W/ usage I meant where you just call the API w/ `phase::begin` and `phase::end` and would replace with `phase::p` scoped_lock mechanism. `phase::p` calling the function of implemented `phase::begin` and `phase::end`, right?

Now the non scoped API implementation should be under separate namespace? I [PRed](https://github.com/BlueBrain/CoreNeuron/pull/168) this as well.

**Comment by tapaswenipathak** [comment]
I don't think I get you. `template <class... TProfilerImpl>` is being implemented as

```c++
using Instrumentor = detail::Instrumentor<
#if defined CORENEURON_CALIPER
    detail::Caliper,
#endif
#if defined(CUDA_PROFILING)
    detail::CudaProfiling,
#endif
#if defined(CRAYPAT)
    detail::CrayPat,
#endif
#if defined(TAU)
    detail::Tau,
#endif
    detail::NullInstrumentor>;
```

W/ usage I meant where you just call the API w/ `phase::begin` and `phase::end` and would replace with `phase::p` scoped_lock mechanism. `phase::p` calling the function of implemented `phase::begin` and `phase::end`, right?

The non scoped API implementation should be under separate namespace? I [PRed](https://github.com/BlueBrain/CoreNeuron/pull/168) this as well.

**Comment by tapaswenipathak** [comment]
@tristan0x ping, do you think I should add anything in this PR? Please let me know.

**Comment by tapaswenipathak** [comment]
hi @tristan0x, do you think I enhance anything else in this PR? Please let me know.

**Comment by tristan0x** [comment]
Hello @tapaswenipathak 
AFAIK, there is no use case for the C++ classes added by this PR. However #168 seems to implement #158 perfectly. So I am in favor of closing this PR

**Pull request closed without merging**
