### PR TITLE
Use only pragma once and no more include guards

### PR DESCRIPTION
**Pull request by alkino**
There were 30 files with pragma once and 42 with include guards

### CODE REVIEW

**Comment by olupton** [comment]
Retest this please Jenkins

**Review by pramodk — APPROVED** [review]
Nice! 

(I hope it won't make #713 merging difficult)

**Comment by alkino** [comment]
I can merge after the other one

**Comment by pramodk** [comment]
@alkino : can you [check the slack discussion ](https://bluebrainproject.slack.com/archives/C0237TFFSTY/p1640002670245800)and we can finalise this PR?

**Review by alexsavulescu — APPROVED** [review]

**Comment by pramodk** [comment]
Retest this please

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
