### PR TITLE
capac functions for CVODE

### PR DESCRIPTION
**Pull request by brunomaga**

### CODE REVIEW

**Comment by brunomaga** [comment]
@nrnhines  these are the div and mul functions from NEURON, with SIMD-friendly data structures for Coreneuron. Can this go in the coreneuron master branch or do you suggest somewhere else?

**Comment by nrnhines** [comment]
Those functions can go here. However they are relevant to CVODE and that is not currently part of
CoreNEURON. So how are they being used?

**Comment by brunomaga** [comment]
Hi Michael @nrnhines. Any update on this?

**Comment by nrnhines** [comment]
I have no objection to this change. But I am apparently not authorized to merge it. I suppose Pramod
can do so.

**Comment by brunomaga** [comment]
thank you.

**Comment by pramodk** [comment]
done, clang-format. will merge once build.

**Pull request merged**
