### PR TITLE
Try to declare dependencies on libcorenrnmech.so properly

### PR DESCRIPTION
**Pull request by olupton**
**Description**
In the CI for neuronsimulator/nrn#1929 we started seeing errors like (https://github.com/neuronsimulator/nrn/runs/8186384877?check_suite_focus=true#step:8:939):
```
gmake[2]: *** No rule to make target 'bin/x86_64/libcorenrnmech.so', needed by 'bin/cmd_interface_test_bin'.  Stop.
```
which do not seem(?) to affect the builds using Ninja.

https://cmake.org/cmake/help/latest/command/add_custom_command.html mentions some restrictions on depending on the outputs of a custom command from other directories. These tweaks seem to avoid the issue.

Also, fix the `nrnivmodl-core` logic for when the `SDKROOT` environment variable is **not** set.

**Use certain branches in CI pipelines.**

CI_BRANCHES:NEURON_BRANCH=master,NMODL_BRANCH=master,SPACK_BRANCH=develop

### CODE REVIEW

**Review by pramodk — APPROVED** [review]
LGTM

**Comment by pramodk** [comment]
Not sure the origin of:

```console
There are not enough slots available in the system to satisfy the 2
[142](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:143)
slots that were requested by the application:
[143](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:144)

[144](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:145)
  special
[145](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:146)

[146](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:147)
Either request fewer slots for your application, or make more slots
[147](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:148)
available for use.
```

**Comment by olupton** [comment]
> Not sure the origin of:
> 
> ```
> There are not enough slots available in the system to satisfy the 2
> [142](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:143)
> slots that were requested by the application:
> [143](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:144)
> 
> [144](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:145)
>   special
> [145](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:146)
> 
> [146](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:147)
> Either request fewer slots for your application, or make more slots
> [147](https://github.com/BlueBrain/CoreNeuron/runs/8223458412?check_suite_focus=true#step:9:148)
> available for use.
> ```

In some places we use `--oversubscribe`: https://github.com/neuronsimulator/nrn/blob/91c278ad60b26cf2ae56d10925001738c06a04b5/test/CMakeLists.txt#L87-L89
we could add that for `parallel::bas`, it seems to be missing, and around here: https://github.com/neuronsimulator/nrn/blob/91c278ad60b26cf2ae56d10925001738c06a04b5/test/CMakeLists.txt#L256-L270

**Comment by pramodk** [comment]
As this PR is independent / standalone, I think OK to merge this? (ignoring this specific CI failure)

**Pull request merged**
