### PR TITLE
Remove external sources from coverage

### PR DESCRIPTION
**Pull request by alkino**
More over split github action in 2 parts (CI and coverage)

CI_BRANCHES:NEURON_BRANCH=master,

### CODE REVIEW

**Review by pramodk — APPROVED** [review]
@alkino : should I merge this?

**Comment by alexsavulescu** [comment]
@alkino do you know why there is no codecov comment ?

**Comment by alkino** [comment]
> @alkino do you know why there is no codecov comment ?

No idea.

**Comment by alexsavulescu** [comment]
One of the benefits of codecov is we get a status of each PR, would be a pity not to have it.

**Comment by pramodk** [comment]
> > @alkino do you know why there is no codecov comment ?
> No idea.

I haven't used codecov. In case anyone wants to take a quick look before merging this?

**Comment by olupton** [comment]
Should this be retested/merged or closed?

**Pull request merged**
